### ISSUE TITLE
Switch to all JS (except for work generation)

### ISSUE THREAD

**Issue by marvinroger** [marvinroger/nanocurrency-js#24]
Doing that should make the package easier to use (no need to call `init` beforehand), and potentially make the code smaller.

Moreover, it will work on environments with broken WebAssembly support (iOS for example).

Obviously, work generation will still use WebAssembly, for performance.

**Comment by marvinroger** [comment]
Released.

**Comment by njakob** [comment]
This decision is kinda sad because it is not possible anymore to use this latest version of the library for vanity address generators. Would you reconsider to have both?

**Comment by marvinroger** [comment]
@njakob have you tried? Performance is way worse? What factor?

The showstopper for WebAssembly was iOS broken support. What's the point of having a Web implementation of something if it does not work on one of the most used mobile OS?

**Comment by njakob** [comment]
@marvinroger For my use-case (https://github.com/njakob/nanoaddr.io) where I use `deriveSecretKey`, `derivePublicKey` and `deriveAddress` within 4 web workers, with the WebAssembly implementation I'm around 30'000 addresses generated per second on my machine where only around 600 with the pure JavaScript implementation.

I totally get the point that a fallback is required for iOS but that should be the developer choice rather than the library itself since the performance penalty is so high.

Therefore would be better imho to provide both implementations.

**Comment by marvinroger** [comment]
I can't find any other use cases for WebAssembly (except for the PoW generation) than a vanity generator. Moreover, maintaining two implementations is cumbersome, to be honest.

Therefore, I propose adding a `deriveAddressFromSeed` function, which would require `init`. The point of this function would be to derive the address #0 from the seed given. Only one, accelerated, function to maintain. For you, it means you would only have to call one function, so your code will be simpler and faster than it already was. Is it ok for you?

**Comment by marvinroger** [comment]
Ping @njakob

**Comment by njakob** [comment]
Sorry to the delay.
Meaning only one function to call to achieve the same result? That would be super cool and might even be faster actually!
