### ISSUE TITLE
Failed to minify the code from nanocurrency-js

### ISSUE THREAD

**Issue by LilleJohs** [marvinroger/nanocurrency-js#44]
I'm trying to make a build of my React front end which is using Nanocurrency-js, but I'm getting an error stating that it can't minify the code from nanocurrency-js. The console redirects me [here](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify), and it basically says that the code has to be compiled to ES5 before being published to NPM since not all browsers support ES6.

**Comment by marvinroger** [comment]
Actually, [the code compiled to ES5](https://github.com/marvinroger/nanocurrency-js/blob/94335d93f13128c37585a3c0176aaf2021eace31/tsconfig.json#L4).

The problem is the [nano-base32](https://github.com/termhn/nano-base32) dependency, which is not. I'll embed it (with the copyright notice, obviously).

**Comment by marvinroger** [comment]
@LilleJohs can you tell me if it's OK for you?

**Comment by LilleJohs** [comment]
Works great! Thanks for making this tool! 👍

**Comment by marvinroger** [comment]
Thanks for the report and the test. 😉
