### ISSUE TITLE
wasm/webassembly bundle

### ISSUE THREAD

**Issue by roccomuso** [marvinroger/nanocurrency-js#59]
I love the module.

Just a couple of questions:
- Are C++ files used for performance improvements?
- Do the bundles have a wasm inclusion? what about the sync `WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB` limit if ran inside electron/browser? it uses async import?
- What if in the build command I put `-s WASM=0` instead of 1?

**Comment by marvinroger** [comment]
* Yes, it's used for faster PoW computation
* It does have the WASM embedded. I don't think the limit is hit, yet. I consider rewriting the C code to AssemblyScript, so it would be a good time to think about it
* The output would be asm.js, not WASM

**Comment by marvinroger** [comment]
@roccomuso Indeed, the 4KB limit is hit.
That's not a problem, though: computing a PoW takes time and blocks the thread, so it should not be used (and cannot because of the limit, anyway). The solution is to use [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), as in the PoW benchmark example: https://marvinroger.github.io/nanocurrency-js/packages/nanocurrency/examples/pow-benchmark/

I am closing this as I know there's room for improvements when it comes to the WASM, but let's track this in https://github.com/marvinroger/nanocurrency-js/issues/17

**Comment by roccomuso** [comment]
Is computing PoW mandatory for a "lite wallet"? that just create, sign and broadcast a transaction? because at this point we can distinguish and in some case avoid the wasm bundle.

**Comment by marvinroger** [comment]
No it's not. Just don't compute the PoW and put the `work` to `null` in the `createBlock` function.

The WASM is only loaded when calling `computeWork`. Also, with tree shaking, if you don't call it in your own code, the WASM won't be present in the final bundle.

**Comment by roccomuso** [comment]
That's great!
